### ISSUE TITLE
 deepseek-moe-16b inference speed is slower than Baichuan-13b

### ISSUE THREAD

**Issue by ifromeast** [deepseek-ai/DeepSeek-MoE#13]
Hi, I have tested inference performance of deepseek-moe-16b and baichuan-13b on A800-80G, the result is 
```
deepseek-moe-16b 14.73 tokens/s
baichuan-13b 22.00 tokens/s
```
Is the result in line with expectations？ Or is there anything wrong with me ?

**Comment by zwd003** [comment]
you can try with this https://github.com/vllm-project/vllm/pull/2453

**Comment by ifromeast** [comment]
Have you tested the performance and comparison of deepseek-moe-16b and dense 13B model under the same environment?

**Comment by zwd003** [comment]
> Have you tested the performance and comparison of deepseek-moe-16b and dense 13B model under the same environment?

now, it's faster than 7b, see link above
