### ISSUE TITLE
The released DeepSeekMoE 16B Base has 3 different vocab size

### ISSUE THREAD

**Issue by drxmy** [deepseek-ai/DeepSeek-MoE#14]
In config.json, vocab size says 102400 which is the same as the shape of "model.embed_tokens.weight". 
But tokenizer.vocab_size says 100000 and len(tokenizer) gives 100015. I have not dig deeper into the code. Is this intended or some bug?

Thank you!

**Comment by DeepSeekPH** [comment]
Hi, you can find the answer on Page-5 of our LLM technique report https://arxiv.org/pdf/2401.02954.pdf  .  
<img width="732" alt="image" src="https://github.com/deepseek-ai/DeepSeek-MoE/assets/152240452/edbd28e3-3f7e-4613-bcf8-d74652089245">

**Comment by drxmy** [comment]
> Hi, you can find the answer on Page-5 of our LLM technique report https://arxiv.org/pdf/2401.02954.pdf . <img alt="image" width="732" src="https://private-user-images.githubusercontent.com/152240452/298443312-edbd28e3-3f7e-4613-bcf8-d74652089245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTAxMzAsIm5iZiI6MTcwNTkwOTgzMCwicGF0aCI6Ii8xNTIyNDA0NTIvMjk4NDQzMzEyLWVkYmQyOGUzLTNmN2UtNDYxMy1iY2Y4LWQ3NDY1MjA4OTI0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwNzUwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2Q3MjM0NjRjZWRiNGRjYzVhZmZhMjVlMjJjMDJmYTcwMTNmNTFiZDRhZmJjZDEyMjA0MDk5NDk4NDAwYzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x78Xd5PGYrRL9PBivwdNf-f_XmHlTHZsopPllz3BQOU">

Thank you，I only read the moe paper
