### ISSUE TITLE
Selective precision In gate and norm may conflict with deepspeed？

### ISSUE THREAD

**Issue by drxmy** [deepseek-ai/DeepSeek-MoE#18]
These lines of  code set norm and gate to be trained in float32
https://github.com/deepseek-ai/DeepSeek-MoE/blob/66edeee5a4f75cbd76e0316229ad101805a90e01/finetune/finetune.py#L238-L247
But with deepspeed's bf16 training, I think its initialization will set all the model to be bf16?
https://github.com/microsoft/DeepSpeed/blob/8ec1cc3be315e2a3276a771e6de706aae91cd330/deepspeed/runtime/engine.py#L1094-L1097
Or they are somehow compatible（an explain would be really appreciate）？

Thank you

**Comment by zwd003** [comment]
Initialization can be done with bf16， we only need to use fp32 for computation during training.
