### ISSUE TITLE
关于flash_attn

### ISSUE THREAD

**Issue by GXKIM** [deepseek-ai/DeepSeek-MoE#20]
torch 2.1
transformers:4.37.1
显卡:A800
手动安装装进去了，但是检测不到flash_attn
直接用pip 装不进去
去github flash_attn 是支持A800的

<img width="329" alt="image" src="https://github.com/deepseek-ai/DeepSeek-MoE/assets/125621025/bec74bc6-a21a-4ae6-952b-3253051830da">

**Comment by zwd003** [comment]
这个是transformers的检测机制问题，可以在源代码目录试试pip install .
