### ISSUE TITLE
非常棒的工作，有没有微信沟通群呢

### ISSUE THREAD

**Issue by dawson-chen** [deepseek-ai/DeepSeek-MoE#22]
如题

**Comment by luofuli** [comment]
扫如下二维码进群 @AllenChennn ：

https://github.com/deepseek-ai/DeepSeek-MoE/blob/main/images/qr.jpeg

**Comment by LPeng625** [comment]
> 扫如下二维码进群 @AllenChennn ：
> 
> https://github.com/deepseek-ai/DeepSeek-MoE/blob/main/images/qr.jpeg

您好，群已满
