### ISSUE TITLE
load erros

### ISSUE THREAD

**Issue by cooper12121** [deepseek-ai/DeepSeek-MoE#24]
Is the flash_attn library necessary to load your model?,when I load your model,there is error:ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
thank you  so much!

**Comment by luofuli** [comment]
cc @zwd003

**Comment by zwd003** [comment]
you could install flash_attn or load the model with attn_implementation="eager"
