### ISSUE TITLE
About expert capacities: Is there token-dropping during training?

### ISSUE THREAD

**Issue by Spico197** [deepseek-ai/DeepSeek-MoE#29]
Hi there, thanks for open-sourcing such an amazing LM~

I'm wondering if you limit the maximum expert capacity by dropping some tokens during training like Switch Transformer.
Since training large MoE models is pretty costly, maybe it's necessary to add a hard constraint to ensure faster expert parallelism?

Thanks again and looking forward to hearing from you.

![image](https://github.com/deepseek-ai/DeepSeek-MoE/assets/22840952/6a2c7216-1dfb-476a-8cdf-65a14dfb3b8f)

**Comment by zwd003** [comment]
@DeepSeekDDM

**Comment by DeepSeekDDM** [comment]
DeepSeekMoE 16B does not have a dropping strategy since it does not use expert parallelism. If using expert parallelism, token dropping will be applied to ensure training efficiency.

**Comment by Spico197** [comment]
Thanks for your valuable comments~ I found the relevant contents from the technical report. Thanks again for your response~

![image](https://github.com/deepseek-ai/DeepSeek-MoE/assets/22840952/cdfa8af4-b08a-4386-80e9-04e57ca95966)
