### ISSUE TITLE
求助：模型无法加载

### ISSUE THREAD

**Issue by KMnO4-zx** [deepseek-ai/DeepSeek-MoE#3]
您好：

我在加载moe模型的时候出现了一些问题

报错显示缺少`flash_attn`而无法加载模型，但在我的环境中是有`flash_attn`的。

为此特地新开了一个conda环境，依然如此。

希望可以得到您的帮助~

![image](https://github.com/deepseek-ai/DeepSeek-MoE/assets/77671993/0eeb35e1-ea53-4813-a3b8-39fea5984636)

**Comment by zwd973-deepseek** [comment]
这是transformers没有检测到flash_attn，可以试试更新transformers到4.36.2版本，使用pip install flash_attn命令安装flash attention，避免从源代码安装

**Comment by KMnO4-zx** [comment]
好的 感谢~

**Comment by GXKIM** [comment]
> 好的 感谢~

A800是不是不能安装flash_attn

**Comment by GXKIM** [comment]
> 这是transformers没有检测到flash_attn，可以试试更新transformers到4.36.2版本，使用pip install flash_attn命令安装flash attention，避免从源代码安装
<img width="234" alt="image" src="https://github.com/deepseek-ai/DeepSeek-MoE/assets/125621025/fda17823-f321-44a7-b8a8-b6c4edceedef">

从官方安装的flash attention ,transformers他也升级了，但是还是识别不到，
<img width="185" alt="image" src="https://github.com/deepseek-ai/DeepSeek-MoE/assets/125621025/def2def2-d297-4fd8-a325-7a114a893ba6">
<img width="673" alt="image" src="https://github.com/deepseek-ai/DeepSeek-MoE/assets/125621025/462ad3a4-7af2-41cb-b248-073e0ca3693d">
