### ISSUE TITLE
开源的MoE模型支持中文吗？

### ISSUE THREAD

**Issue by uloveqian2021** [deepseek-ai/DeepSeek-MoE#6]

**Comment by zhang001122** [comment]
实际测试了 支持中文 token中也不少中文词，目前 使用 transform的generate做推理   希望能尽快适配vllm或者 修改为 llama2的基座

**Comment by luofuli** [comment]
支持的，我们在中英语料上训练的

**Comment by luofuli** [comment]
vllm正在适配中

**Comment by zwd003** [comment]
> 实际测试了 支持中文 token中也不少中文词，目前 使用 transform的generate做推理 希望能尽快适配vllm或者 修改为 llama2的基座

已经支持vllm，请参考https://github.com/vllm-project/vllm/pull/2453
