### ISSUE TITLE
您们能够开源复现模型架构的训练项目吗?

### ISSUE THREAD

**Issue by win10ogod** [deepseek-ai/DeepSeek-MoE#7]
您们能够开源复现模型架构的训练项目吗?

**Comment by luofuli** [comment]
暂无计划

**Comment by win10ogod** [comment]
> 暂无计划
那您们能将模型架构加入lit-gpt[](https://github.com/Lightning-AI/lit-gpt)或是llama2.c[](https://github.com/karpathy/llama2.c)吗?

**Comment by zwd003** [comment]
> > 暂无计划
> 
> 那您们能将模型架构加入lit-gpt或是llama2.c吗?

我们暂时只支持了vllm，其他的还在计划中或者看社区支持
