### ISSUE TITLE
#feature request# DeepSeek-Moe for code

### ISSUE THREAD

**Issue by Xingxiangrui** [deepseek-ai/DeepSeek-MoE#8]
Thank you for your excellent work.
DeepSeek-MoE and DeepSeek-Coder are impressive.

Will you combine DeepSeed Coder with MoE architure? 
This would bring significant performance improvement.

**Comment by luofuli** [comment]
> Thank you for your excellent work. DeepSeek-MoE and DeepSeek-Coder are impressive.
> 
> Will you combine DeepSeed Coder with MoE architure? This would bring significant performance improvement.

Our next coder model is based on MoE.
